language: r
sudo: false
cache: packages

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)"

addons:
  apt:
    packages:
    - libmagick++-dev
    - libglu1-mesa-dev

jobs:
  include:
    - r: oldrel
    - r: release
      before_install:
        - "curl https://xran.yihui.org/.gitconfig -o ~/.gitconfig"
      after_success:
        - "(curl https://xran.yihui.org/r-xran | bash)"
    - r: devel
